# Generated by Django 3.0.4 on 2020-03-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
