# Generated by Django 3.0.4 on 2020-03-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songo', '0004_auto_20200329_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='a_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songo.Artist'),
        ),
    ]
