# Generated by Django 3.0.4 on 2020-03-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songo', '0006_song_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='dob',
            field=models.DateField(),
        ),
    ]
