# Generated by Django 3.0.4 on 2020-03-30 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songo', '0007_auto_20200330_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songo.Artist')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songo.Song')),
            ],
        ),
    ]
