# Generated by Django 3.0.4 on 2020-03-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songo', '0008_song_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='a_id',
        ),
    ]
