# Generated by Django 3.0.4 on 2020-03-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songo', '0009_remove_song_a_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='a_id',
            field=models.ManyToManyField(to='songo.Artist'),
        ),
    ]
