# Generated by Django 3.0.4 on 2020-03-31 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songo', '0010_song_a_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songo.Artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songo.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song')},
                'index_together': {('user', 'song')},
            },
        ),
        migrations.DeleteModel(
            name='Song_list',
        ),
    ]
